apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistry2764.azurecr.io/frontend-vue # 이미지 주소 변경필요
    newTag: main-20240809074020

commonLabels:
  app: frontend-vue
  environment: dev
